Issue #326 - supporting upgrade files and version
zold-io/zold pull request #496
Opened 2018-10-17 15:40 UTC by emilianodellacasa

Solving issue #326 allowing Zold to upgrade itself using rb scripts.

I used the tests that had already been written but skipped at the moment.

Please note that I had to disable Eval check in Rubocop to avoid the code smell: in fact, using the "eval" function is a potential security breach, but it should be ok as we are executing only scripts that are in a specific directory of the repository.

2018-10-17 15:47 UTC, 0crat commented
Job [#496](https://github.com/zold-io/zold/issues/496) is now in scope, role is `REV`

<!-- https://www.0crat.com/footprint/CAZPZR9FS/2901542365, version: 0.36.2, hash: ${buildNumber} -->

2018-10-17 16:47 UTC, 0crat commented
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `REV` is banned at [#496](https://github.com/zold-io/zold/issues/496); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

<!-- https://www.0crat.com/footprint/CAZPZR9FS/2901644884, version: 0.36.2, hash: ${buildNumber} -->

2018-10-27 18:37 UTC, 0crat commented
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `REV` is banned at [#496](https://github.com/zold-io/zold/issues/496); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

<!-- https://www.0crat.com/footprint/CAZPZR9FS/33a8f996-5294-4b39-b420-03b5e4e45f51, version: 0.37.4, hash: ${buildNumber} -->

2018-11-03 06:39 UTC, 0crat commented
@tsuhachev[/z](https://www.0crat.com/u/tsuhachev) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

<!-- https://www.0crat.com/footprint/CAZPZR9FS/e38e2b39-09b5-417f-8232-7d7a388ff283, version: 0.37.5, hash: ${buildNumber} -->

2026-06-13 08:13 UTC, yegor256 commented
Please fix the merge conflicts so this pull request can be merged.

2026-06-14 19:21 UTC, emilianodellacasa commented
Ready!

2026-06-17 20:10 UTC, kreinba requested changes
The change wires up the upgrade machinery and turns the skipped tests back on, but several defects in the version-parsing and script-execution path keep it from working for any future release past 0.0.9. Six inline comments below; the most serious is that apply never writes the new version back, so every run replays every script. CI is not configured on the head commit.

2026-06-17 20:10 UTC, kreinba commented on lib/zold/version_file.rb
> +    end
apply never writes the new version to the version file after executing the script, so current_version stays at its previous value and every subsequent run replays every script in the directory. After eval succeeds, write `version` back to `File.join(@path, 'version')` so the next call sees it as already applied.

2026-06-17 20:10 UTC, kreinba commented on lib/zold/version_file.rb
> +      file_name.scan(/\d\.\d\.\d/).last
`\d` only matches a single digit, so `0.0.10` is parsed as `0.0.1` and the script is treated as identical to the previous patch. Use `\d+\.\d+\.\d+` to support multi-digit components, otherwise zold cannot upgrade past 0.0.9.

2026-06-17 20:10 UTC, kreinba commented on lib/zold/version_file.rb
> +      return unless ::Gem::Version.new(version) > current_version
When extract_version_from_script_name returns nil (script name does not contain a `\d.\d.\d` substring) this raises ArgumentError from Gem::Version.new(nil). Guard with `return if version.nil?` before constructing the Gem::Version.

2026-06-17 20:10 UTC, kreinba commented on lib/zold/upgrades.rb
> +      Dir.glob("#{@directory}/*.rb").grep(/\d\.\d\.\d\.rb/).sort.each do |script|
`.sort` is lexicographic, so once multi-digit versions are allowed `0.0.10.rb` sorts before `0.0.2.rb` and scripts run out of order. Sort by `Gem::Version` parsed from each filename instead, e.g. `.sort_by { |s| Gem::Version.new(File.basename(s, '.rb')) }`.

2026-06-17 20:10 UTC, kreinba commented on .rubocop.yml
> +  Enabled: false
Disabling Security/Eval globally turns the check off for the whole codebase. Either narrow the exception with `Exclude: [lib/zold/version_file.rb]` here, or place a single `# rubocop:disable Security/Eval` directive on the eval line in version_file.rb so the check still guards the rest of the source tree.

2026-06-17 20:10 UTC, kreinba commented on lib/zold/version_file.rb
> +      eval(code)
eval runs the script inside the VersionFile instance, exposing @path, @log, @current_version and the private helpers below to arbitrary upgrade code. Pass a fresh binding (`eval(code, TOPLEVEL_BINDING, script)`) or use `Kernel.load script` so upgrade scripts get their own scope and stack traces point at the script file rather than at version_file.rb.

2026-06-21 20:15 UTC, edmoffo requested changes
The upgrade script filter and the version-tracking logic are both wrong, and the rubocop disable is broader than the eval call it shields. Re-running the upgrade chain replays every pending script because `apply` never persists the new version to disk. Three inline comments below.

2026-06-21 20:15 UTC, edmoffo commented on lib/zold/upgrades.rb
> +      Dir.glob("#{@directory}/*.rb").grep(/\d\.\d\.\d\.rb/).sort.each do |script|
Two problems with `/\d\.\d\.\d\.rb/`. The pattern is unanchored, so `0.0.1.rb.bak` and `xx0.0.1.rb` both match; the `.` is regex "any character", so `0a0b1xrb` matches too. And `\d` is a single digit, so as soon as a version reaches `0.0.10` or `0.1.0` the matching script gets silently skipped. Use `/\A\d+\.\d+\.\d+\.rb\z/`.

2026-06-21 20:15 UTC, edmoffo commented on lib/zold/version_file.rb
> +      eval(code)
`apply` runs the script via `eval` but never writes the script's version into `version_file`. The next call to `run` re-reads the same `current_version` from disk and runs every higher-versioned script again. Persist the new version after a successful `eval`, e.g. `File.write(version_file, version)` plus `@current_version = ::Gem::Version.new(version)` so the memoized value matches the file.

2026-06-21 20:15 UTC, edmoffo commented on .rubocop.yml
> +Security/Eval:
Disabling `Security/Eval` globally hides every future `eval` in the codebase, not just the one in `VersionFile#apply`. Re-enable it here and scope the exception to the single call with `# rubocop:disable Security/Eval` / `# rubocop:enable Security/Eval` around line 21 of `lib/zold/version_file.rb`.

2026-07-27 17:41 UTC, yegor256 commented
We are closing this pull request, because it has merge conflicts with `master` and has been open for more than a month. Please, forgive us for this: it says nothing about the quality of your work, it's just housekeeping.

If the change still matters to you, please submit a new pull request. It may be very similar to this one, but it has to take into account everything that landed in `master` since then.

Thank you for contributing, and sorry again for the inconvenience!

2026-07-27 17:41 UTC, closed without merging