#610 Add `zold node --nohup-log-rotate` option
zold-io/zold pull request #755
Opened 2019-05-08 02:52 UTC by v-kolesnikov

Many thanks for your contribution, we truly appreciate it. We will appreciate it even more, if you make sure that you can say "YES" to each point in this short checklist:

  - You made a small amount of changes (less than 100 lines, less than 10 files)
  - You made changes related to only one bug (create separate PRs for separate problems)
  - You are ready to defend your changes (there will be a code review)
  - You don't touch what you don't understand
  - You ran the build locally and it passed

This article will help you understand what we are looking for: http://www.yegor256.com/2015/02/09/serious-code-reviewer.html

Thank you for your contribution!

2019-05-08 02:52 UTC, 0crat commented
Job [#755](https://github.com/zold-io/zold/issues/755) is now in scope, role is `REV`

<!-- https://www.0crat.com/footprint/CAZPZR9FS/6e33d098-a486-48fa-a44c-74d70b2d2f59, version: 0.46.9, hash: ${buildNumber} -->

2022-08-18 03:26 UTC, 0crat commented
This pull request [#755](https://github.com/zold-io/zold/issues/755) is assigned to @anaumov[/z](https://www.0crat.com/u/anaumov), here is [why](https://www.0crat.com/footprint/CAZPZR9FS/d6191a9e-cb4c-4754-816c-08a4661b5d31); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @yegor256[/z](https://www.0crat.com/u/yegor256) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be a monetary reward for this job

<!-- https://www.0crat.com/footprint/CAZPZR9FS/b8b92d22-d82a-4acd-9c1b-35255d054299, version: 1.0-SNAPSHOT, hash: 97d425378 -->

2026-06-17 20:10 UTC, kreinba requested changes
The new --nohup-log-rotate option and the NohupLogRotate wrapper match issue #610, but the diff also touches the HUP and TERM signal handlers without mention in the title or body, the rotation argument is not validated against the values advertised in the help text, and the new test writes to a hard-coded path under /tmp. Four inline comments below.

2026-06-17 20:10 UTC, kreinba commented on lib/zold/commands/node.rb
> +          Thread.new { nohup_log.print("Received HUP, ignoring...\n") }.join
Wrapping the trap body in a Thread that is immediately joined is unrelated to the log-rotation feature this PR advertises and changes behavior at TERM (joining can block trap return). Drop this from the PR and file a separate issue for signal-handling work, or move the join-from-trap workaround to its own commit so the rotation change is reviewable in isolation.

2026-06-17 20:10 UTC, kreinba commented on lib/zold/commands/node.rb
> +          'Frequency of the log file rotation (daily, weekly or monthly)'
The help text promises `daily, weekly or monthly` but the option is passed straight into ::Logger.new without validation. Reject other values with a clear error inside the run block (`raise unless %w[daily weekly monthly].include?(opts['nohup-log-rotate'])`) so a typo surfaces in the CLI rather than as a stack trace from inside Logger.

2026-06-17 20:10 UTC, kreinba commented on test/node/test_nohup_log_rotate.rb
> +  def test_print
`/tmp/zold.log` is a hard-coded path that collides with any other test or running zold process on the same machine and is not cleaned up if the test crashes before the ensure. Wrap the body in `Dir.mktmpdir do |dir|` and use `File.join(dir, 'zold.log')` so the path is per-test and torn down automatically.

2026-06-17 20:10 UTC, kreinba commented on test/node/test_nohup_log_rotate.rb
> +
`require 'minitest/autorun'` is redundant: `test__helper` loaded the line above already pulls in minitest. Drop this require to keep the per-test boilerplate consistent with the rest of test/.

2026-06-21 20:15 UTC, edmoffo reviewed
The rotation option works in the happy path but silently swallows invalid rotation values, drops the existing truncate semantics, and the new test writes to a shared `/tmp/zold.log`. Three inline notes.

2026-06-21 20:15 UTC, edmoffo commented on lib/zold/commands/node.rb
> +        o.string '--nohup-log-rotate',
Help text limits the value to `daily`, `weekly`, or `monthly`, but the code passes whatever the user typed straight into `Logger.new`. Anything else (`hourly`, `weeklys`, a typo) is accepted at parse time and only blows up later inside the log path. Validate the value here against the documented set and refuse to start the node when it does not match.

2026-06-21 20:15 UTC, edmoffo commented on lib/zold/commands/node.rb
> +    class NohupLogRotate
`NohupLogRotate` ignores `--nohup-log-truncate`, so as soon as the user passes `--nohup-log-rotate` the size cap defined by the existing option silently stops applying. Either honor `--nohup-log-truncate` here too (`Logger.new(file_path, rotation_age, shift_size: limit)` does what you want) or document that the two options are mutually exclusive and reject the combination at parse time.

2026-06-21 20:15 UTC, edmoffo commented on test/node/test_nohup_log_rotate.rb
> +    logger = Zold::Node::NohupLogRotate.new('/tmp/zold.log', 'daily')
Hardcoding `/tmp/zold.log` makes the test race with itself when the suite runs in parallel (the `ensure` block deletes the file out from under another test) and leaks state between runs if the test is interrupted before the cleanup. Use `Dir.mktmpdir` like the rest of the suite and join the log path inside it.

2026-07-27 17:41 UTC, yegor256 commented
We are closing this pull request, because it has merge conflicts with `master` and has been open for more than a month. Please, forgive us for this: it says nothing about the quality of your work, it's just housekeeping.

If the change still matters to you, please submit a new pull request. It may be very similar to this one, but it has to take into account everything that landed in `master` since then.

Thank you for contributing, and sorry again for the inconvenience!

2026-07-27 17:41 UTC, closed without merging